/**
 * CLASP Security & Capability Tokens Example
 *
 * Demonstrates authentication and authorization using CPSK tokens.
 * Shows how to:
 * - Connect with a capability token
 * - Use scoped permissions (read/write/admin)
 * - Handle unauthorized access attempts
 *
 * Usage:
 *   # Start router with security enabled
 *   cargo run -p clasp-router-server -- --security token --listen 0.0.0.0:7330
 *
 *   # Generate tokens
 *   cargo run -p clasp-router-server -- token create --scopes "read:/**"
 *   cargo run -p clasp-router-server -- token create --scopes "read:/**,write:/lights/**"
 *
 *   # Run example with token
 *   CLASP_TOKEN=cpsk_xxx node security-tokens.js
 */

import { Clasp } from '@clasp-to/core';

const CLASP_URL = process.env.CLASP_URL || 'ws://localhost:7330';

// Example tokens with different scopes (in production, these would be generated by the server)
const TOKENS = {
  readOnly: process.env.READ_TOKEN || 'cpsk_read_only_demo_token',
  lightsControl: process.env.LIGHTS_TOKEN || 'cpsk_lights_control_demo_token',
  admin: process.env.ADMIN_TOKEN || 'cpsk_admin_demo_token'
};

async function demonstrateReadOnlyAccess() {
  console.log('\n=== Read-Only Token Demo ===');
  console.log('Scope: read:/**');

  const client = new Clasp(CLASP_URL);

  try {
    // Connect with read-only token
    await client.connect({
      token: TOKENS.readOnly,
      name: 'Read-Only Client'
    });
    console.log('Connected with read-only token');

    // Subscribe works (we have read access)
    client.on('/lights/**', (value, address) => {
      console.log(`[READ] ${address} = ${value}`);
    });
    console.log('Subscribed to /lights/** - OK');

    // Try to write (should fail)
    try {
      await client.set('/lights/1/brightness', 0.5);
      console.log('Write succeeded - UNEXPECTED!');
    } catch (err) {
      console.log(`Write denied as expected: ${err.code}`);
    }

    await client.disconnect();
  } catch (err) {
    console.error('Connection failed:', err.message);
  }
}

async function demonstrateScopedWrite() {
  console.log('\n=== Scoped Write Token Demo ===');
  console.log('Scope: read:/**,write:/lights/**');

  const client = new Clasp(CLASP_URL);

  try {
    await client.connect({
      token: TOKENS.lightsControl,
      name: 'Lights Controller'
    });
    console.log('Connected with lights control token');

    // Read from anywhere
    client.on('/sensors/**', (value, address) => {
      console.log(`[READ] ${address} = ${value}`);
    });
    console.log('Subscribed to /sensors/** - OK');

    // Write to lights namespace (allowed)
    await client.set('/lights/living-room/brightness', 0.75);
    console.log('Set /lights/living-room/brightness = 0.75 - OK');

    await client.set('/lights/kitchen/color', { r: 255, g: 200, b: 150 });
    console.log('Set /lights/kitchen/color - OK');

    // Try to write outside allowed namespace (should fail)
    try {
      await client.set('/audio/master/volume', 0.8);
      console.log('Write to /audio succeeded - UNEXPECTED!');
    } catch (err) {
      console.log(`Write to /audio denied as expected: ${err.code}`);
    }

    await client.disconnect();
  } catch (err) {
    console.error('Connection failed:', err.message);
  }
}

async function demonstrateAdminAccess() {
  console.log('\n=== Admin Token Demo ===');
  console.log('Scope: admin:/**');

  const client = new Clasp(CLASP_URL);

  try {
    await client.connect({
      token: TOKENS.admin,
      name: 'Admin Client'
    });
    console.log('Connected with admin token');

    // Admin can read everything
    client.on('/**', (value, address) => {
      console.log(`[ADMIN READ] ${address} = ${JSON.stringify(value)}`);
    });
    console.log('Subscribed to /** - OK');

    // Admin can write everywhere
    await client.set('/lights/1/brightness', 1.0);
    await client.set('/audio/master/volume', 0.7);
    await client.set('/system/config/debug', true);
    console.log('Admin writes to all namespaces - OK');

    // Admin can emit events
    await client.emit('/system/admin/action', { action: 'test', by: 'admin' });
    console.log('Admin event emission - OK');

    await client.disconnect();
  } catch (err) {
    console.error('Connection failed:', err.message);
  }
}

async function demonstrateTokenRefresh() {
  console.log('\n=== Token Refresh Demo ===');

  const client = new Clasp(CLASP_URL);

  try {
    await client.connect({
      token: TOKENS.readOnly,
      name: 'Refreshable Client'
    });
    console.log('Connected with initial token');

    // Upgrade to a more permissive token
    console.log('Upgrading token...');
    await client.refreshToken(TOKENS.lightsControl);
    console.log('Token upgraded to lights control');

    // Now writes to lights should work
    await client.set('/lights/upgraded/brightness', 0.5);
    console.log('Write after upgrade - OK');

    await client.disconnect();
  } catch (err) {
    console.error('Token refresh failed:', err.message);
  }
}

async function main() {
  console.log('=== CLASP Security & Tokens Example ===');
  console.log(`Server: ${CLASP_URL}`);

  // Check if server requires authentication
  const testClient = new Clasp(CLASP_URL);
  try {
    await testClient.connect({ name: 'Test' });
    console.log('\nNote: Server is in OPEN mode (no authentication required)');
    console.log('Run router with --security token to test authentication.');
    await testClient.disconnect();
    return;
  } catch (err) {
    if (err.code === 'AUTH_REQUIRED') {
      console.log('\nServer requires authentication - proceeding with demos');
    } else {
      throw err;
    }
  }

  await demonstrateReadOnlyAccess();
  await demonstrateScopedWrite();
  await demonstrateAdminAccess();
  await demonstrateTokenRefresh();

  console.log('\n=== All security demos complete ===');
}

main().catch(console.error);
