# CLASP Relay -- generated by clasp-setup
# Reconfigure: clasp-setup
# Docs: https://docs.clasp.to/deployment/docker

services:
  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - /opt/clasp/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
    depends_on:
      - relay
    restart: unless-stopped

  relay:
    image: ghcr.io/lumencanvas/clasp-relay:latest
    ports:
      {{MQTT_PORT}}
      {{OSC_PORT}}
    environment:
      RUST_LOG: info
      LOG_FORMAT: json
    command:
      - "--ws-port"
      - "7330"
      - "--health-port"
      - "7360"
      - "--host"
      - "0.0.0.0"
      - "--name"
      - "{{DOMAIN}}"
      {{AUTH_ARGS}}
      {{PERSIST_ARGS}}
      {{MQTT_ARGS}}
      {{OSC_ARGS}}
      {{RULES_ARGS}}
      {{METRICS_ARGS}}
      {{CORS_ARGS}}
    volumes:
      - /var/lib/clasp:/data
    restart: unless-stopped

  {{METRICS_SERVICE}}

volumes:
  caddy-data:
  caddy-config:
