/**
 * Emoji data organized by category.
 * ~500 common emojis across 8 categories.
 */

export const EMOJI_CATEGORIES = [
  'Smileys',
  'People',
  'Animals',
  'Food',
  'Activities',
  'Travel',
  'Objects',
  'Symbols',
]

export const EMOJIS = [
  // Smileys
  { emoji: '😀', name: 'grinning face', keywords: ['happy', 'smile'], category: 'Smileys' },
  { emoji: '😃', name: 'grinning face big eyes', keywords: ['happy', 'joy'], category: 'Smileys' },
  { emoji: '😄', name: 'grinning squinting face', keywords: ['happy', 'laugh'], category: 'Smileys' },
  { emoji: '😁', name: 'beaming face', keywords: ['grin', 'happy'], category: 'Smileys' },
  { emoji: '😆', name: 'squinting face', keywords: ['laugh', 'happy'], category: 'Smileys' },
  { emoji: '😅', name: 'sweat smile', keywords: ['hot', 'laugh'], category: 'Smileys' },
  { emoji: '🤣', name: 'rolling on floor', keywords: ['rofl', 'laugh'], category: 'Smileys' },
  { emoji: '😂', name: 'face with tears of joy', keywords: ['laugh', 'cry'], category: 'Smileys' },
  { emoji: '🙂', name: 'slightly smiling', keywords: ['smile'], category: 'Smileys' },
  { emoji: '🙃', name: 'upside down face', keywords: ['sarcasm'], category: 'Smileys' },
  { emoji: '😉', name: 'winking face', keywords: ['wink'], category: 'Smileys' },
  { emoji: '😊', name: 'smiling with smiling eyes', keywords: ['blush', 'happy'], category: 'Smileys' },
  { emoji: '😇', name: 'smiling with halo', keywords: ['angel', 'innocent'], category: 'Smileys' },
  { emoji: '🥰', name: 'smiling with hearts', keywords: ['love', 'crush'], category: 'Smileys' },
  { emoji: '😍', name: 'heart eyes', keywords: ['love', 'crush'], category: 'Smileys' },
  { emoji: '🤩', name: 'star struck', keywords: ['excited', 'wow'], category: 'Smileys' },
  { emoji: '😘', name: 'face blowing kiss', keywords: ['kiss', 'love'], category: 'Smileys' },
  { emoji: '😗', name: 'kissing face', keywords: ['kiss'], category: 'Smileys' },
  { emoji: '😚', name: 'kissing closed eyes', keywords: ['kiss'], category: 'Smileys' },
  { emoji: '😙', name: 'kissing smiling eyes', keywords: ['kiss'], category: 'Smileys' },
  { emoji: '🥲', name: 'smiling with tear', keywords: ['sad', 'happy'], category: 'Smileys' },
  { emoji: '😋', name: 'face savoring food', keywords: ['yummy', 'delicious'], category: 'Smileys' },
  { emoji: '😛', name: 'face with tongue', keywords: ['playful'], category: 'Smileys' },
  { emoji: '😜', name: 'winking with tongue', keywords: ['playful', 'silly'], category: 'Smileys' },
  { emoji: '🤪', name: 'zany face', keywords: ['crazy', 'wild'], category: 'Smileys' },
  { emoji: '😝', name: 'squinting with tongue', keywords: ['playful'], category: 'Smileys' },
  { emoji: '🤑', name: 'money mouth', keywords: ['rich', 'money'], category: 'Smileys' },
  { emoji: '🤗', name: 'hugging face', keywords: ['hug', 'love'], category: 'Smileys' },
  { emoji: '🤭', name: 'face with hand over mouth', keywords: ['oops', 'giggle'], category: 'Smileys' },
  { emoji: '🤫', name: 'shushing face', keywords: ['quiet', 'secret'], category: 'Smileys' },
  { emoji: '🤔', name: 'thinking face', keywords: ['think', 'hmm'], category: 'Smileys' },
  { emoji: '🫡', name: 'saluting face', keywords: ['salute', 'respect'], category: 'Smileys' },
  { emoji: '🤐', name: 'zipper mouth', keywords: ['quiet', 'secret'], category: 'Smileys' },
  { emoji: '🤨', name: 'raised eyebrow', keywords: ['skeptical', 'sus'], category: 'Smileys' },
  { emoji: '😐', name: 'neutral face', keywords: ['meh', 'blank'], category: 'Smileys' },
  { emoji: '😑', name: 'expressionless', keywords: ['blank', 'unimpressed'], category: 'Smileys' },
  { emoji: '😶', name: 'no mouth', keywords: ['silent', 'speechless'], category: 'Smileys' },
  { emoji: '🫠', name: 'melting face', keywords: ['hot', 'melt'], category: 'Smileys' },
  { emoji: '😏', name: 'smirking face', keywords: ['smirk', 'sly'], category: 'Smileys' },
  { emoji: '😒', name: 'unamused face', keywords: ['meh', 'bored'], category: 'Smileys' },
  { emoji: '🙄', name: 'rolling eyes', keywords: ['annoyed', 'whatever'], category: 'Smileys' },
  { emoji: '😬', name: 'grimacing face', keywords: ['awkward', 'yikes'], category: 'Smileys' },
  { emoji: '😮‍💨', name: 'exhaling face', keywords: ['sigh', 'relief'], category: 'Smileys' },
  { emoji: '🤥', name: 'lying face', keywords: ['pinocchio', 'lie'], category: 'Smileys' },
  { emoji: '😌', name: 'relieved face', keywords: ['calm', 'relief'], category: 'Smileys' },
  { emoji: '😔', name: 'pensive face', keywords: ['sad', 'thoughtful'], category: 'Smileys' },
  { emoji: '😪', name: 'sleepy face', keywords: ['tired', 'sleep'], category: 'Smileys' },
  { emoji: '🤤', name: 'drooling face', keywords: ['drool', 'yummy'], category: 'Smileys' },
  { emoji: '😴', name: 'sleeping face', keywords: ['sleep', 'zzz'], category: 'Smileys' },
  { emoji: '😷', name: 'medical mask', keywords: ['sick', 'mask'], category: 'Smileys' },
  { emoji: '🤒', name: 'face with thermometer', keywords: ['sick', 'fever'], category: 'Smileys' },
  { emoji: '🤕', name: 'head bandage', keywords: ['hurt', 'injured'], category: 'Smileys' },
  { emoji: '🤢', name: 'nauseated face', keywords: ['sick', 'gross'], category: 'Smileys' },
  { emoji: '🤮', name: 'vomiting face', keywords: ['sick', 'puke'], category: 'Smileys' },
  { emoji: '🥵', name: 'hot face', keywords: ['heat', 'sweating'], category: 'Smileys' },
  { emoji: '🥶', name: 'cold face', keywords: ['freezing', 'cold'], category: 'Smileys' },
  { emoji: '😵', name: 'knocked out', keywords: ['dizzy', 'dead'], category: 'Smileys' },
  { emoji: '🤯', name: 'exploding head', keywords: ['mind blown', 'shocked'], category: 'Smileys' },
  { emoji: '🥳', name: 'partying face', keywords: ['party', 'celebrate'], category: 'Smileys' },
  { emoji: '🥸', name: 'disguised face', keywords: ['disguise', 'incognito'], category: 'Smileys' },
  { emoji: '😎', name: 'sunglasses face', keywords: ['cool', 'confident'], category: 'Smileys' },
  { emoji: '🤓', name: 'nerd face', keywords: ['nerd', 'geek'], category: 'Smileys' },
  { emoji: '🧐', name: 'monocle face', keywords: ['inspect', 'curious'], category: 'Smileys' },
  { emoji: '😕', name: 'confused face', keywords: ['confused', 'puzzled'], category: 'Smileys' },
  { emoji: '🫤', name: 'face with diagonal mouth', keywords: ['meh', 'unsure'], category: 'Smileys' },
  { emoji: '😟', name: 'worried face', keywords: ['worried', 'nervous'], category: 'Smileys' },
  { emoji: '🙁', name: 'slightly frowning', keywords: ['sad', 'disappointed'], category: 'Smileys' },
  { emoji: '😮', name: 'face with open mouth', keywords: ['surprised', 'wow'], category: 'Smileys' },
  { emoji: '😯', name: 'hushed face', keywords: ['surprised', 'quiet'], category: 'Smileys' },
  { emoji: '😲', name: 'astonished face', keywords: ['shocked', 'wow'], category: 'Smileys' },
  { emoji: '😳', name: 'flushed face', keywords: ['embarrassed', 'blush'], category: 'Smileys' },
  { emoji: '🥺', name: 'pleading face', keywords: ['please', 'puppy eyes'], category: 'Smileys' },
  { emoji: '🥹', name: 'holding back tears', keywords: ['emotional', 'touched'], category: 'Smileys' },
  { emoji: '😦', name: 'frowning open mouth', keywords: ['anguish'], category: 'Smileys' },
  { emoji: '😧', name: 'anguished face', keywords: ['shocked', 'distressed'], category: 'Smileys' },
  { emoji: '😨', name: 'fearful face', keywords: ['scared', 'fear'], category: 'Smileys' },
  { emoji: '😰', name: 'anxious face', keywords: ['nervous', 'sweat'], category: 'Smileys' },
  { emoji: '😥', name: 'sad but relieved', keywords: ['whew', 'sad'], category: 'Smileys' },
  { emoji: '😢', name: 'crying face', keywords: ['cry', 'sad', 'tear'], category: 'Smileys' },
  { emoji: '😭', name: 'loudly crying', keywords: ['sob', 'cry', 'sad'], category: 'Smileys' },
  { emoji: '😱', name: 'face screaming', keywords: ['scream', 'fear', 'horror'], category: 'Smileys' },
  { emoji: '😖', name: 'confounded face', keywords: ['confused', 'quizzical'], category: 'Smileys' },
  { emoji: '😣', name: 'persevering face', keywords: ['struggle'], category: 'Smileys' },
  { emoji: '😞', name: 'disappointed face', keywords: ['sad', 'upset'], category: 'Smileys' },
  { emoji: '😓', name: 'downcast with sweat', keywords: ['sad', 'hard work'], category: 'Smileys' },
  { emoji: '😩', name: 'weary face', keywords: ['tired', 'frustrated'], category: 'Smileys' },
  { emoji: '😫', name: 'tired face', keywords: ['exhausted', 'whine'], category: 'Smileys' },
  { emoji: '🥱', name: 'yawning face', keywords: ['bored', 'tired', 'yawn'], category: 'Smileys' },
  { emoji: '😤', name: 'huffing face', keywords: ['angry', 'frustrated'], category: 'Smileys' },
  { emoji: '😡', name: 'pouting face', keywords: ['angry', 'mad', 'rage'], category: 'Smileys' },
  { emoji: '😠', name: 'angry face', keywords: ['mad', 'annoyed'], category: 'Smileys' },
  { emoji: '🤬', name: 'cursing face', keywords: ['swear', 'angry'], category: 'Smileys' },
  { emoji: '👿', name: 'angry devil', keywords: ['devil', 'evil'], category: 'Smileys' },
  { emoji: '💀', name: 'skull', keywords: ['dead', 'death', 'rip'], category: 'Smileys' },
  { emoji: '💩', name: 'pile of poo', keywords: ['poop', 'shit'], category: 'Smileys' },
  { emoji: '🤡', name: 'clown face', keywords: ['clown', 'fool'], category: 'Smileys' },
  { emoji: '👹', name: 'ogre', keywords: ['monster', 'scary'], category: 'Smileys' },
  { emoji: '👻', name: 'ghost', keywords: ['halloween', 'boo'], category: 'Smileys' },
  { emoji: '👽', name: 'alien', keywords: ['ufo', 'space'], category: 'Smileys' },
  { emoji: '🤖', name: 'robot', keywords: ['bot', 'machine'], category: 'Smileys' },
  { emoji: '🫶', name: 'heart hands', keywords: ['love', 'heart'], category: 'Smileys' },

  // People
  { emoji: '👋', name: 'waving hand', keywords: ['hello', 'hi', 'wave', 'bye'], category: 'People' },
  { emoji: '🤚', name: 'raised back of hand', keywords: ['stop'], category: 'People' },
  { emoji: '🖐️', name: 'hand with fingers splayed', keywords: ['high five'], category: 'People' },
  { emoji: '✋', name: 'raised hand', keywords: ['stop', 'high five'], category: 'People' },
  { emoji: '🖖', name: 'vulcan salute', keywords: ['spock', 'star trek'], category: 'People' },
  { emoji: '👌', name: 'ok hand', keywords: ['ok', 'perfect'], category: 'People' },
  { emoji: '🤌', name: 'pinched fingers', keywords: ['italian', 'what'], category: 'People' },
  { emoji: '🤏', name: 'pinching hand', keywords: ['small', 'tiny'], category: 'People' },
  { emoji: '✌️', name: 'victory hand', keywords: ['peace', 'two'], category: 'People' },
  { emoji: '🤞', name: 'crossed fingers', keywords: ['luck', 'hope'], category: 'People' },
  { emoji: '🫰', name: 'hand with index and thumb crossed', keywords: ['money', 'snap'], category: 'People' },
  { emoji: '🤟', name: 'love you gesture', keywords: ['love', 'rock'], category: 'People' },
  { emoji: '🤘', name: 'sign of the horns', keywords: ['rock', 'metal'], category: 'People' },
  { emoji: '🤙', name: 'call me hand', keywords: ['phone', 'shaka'], category: 'People' },
  { emoji: '👈', name: 'pointing left', keywords: ['left', 'direction'], category: 'People' },
  { emoji: '👉', name: 'pointing right', keywords: ['right', 'direction'], category: 'People' },
  { emoji: '👆', name: 'pointing up', keywords: ['up'], category: 'People' },
  { emoji: '👇', name: 'pointing down', keywords: ['down'], category: 'People' },
  { emoji: '☝️', name: 'index pointing up', keywords: ['one', 'up'], category: 'People' },
  { emoji: '👍', name: 'thumbs up', keywords: ['yes', 'good', 'ok', 'like'], category: 'People' },
  { emoji: '👎', name: 'thumbs down', keywords: ['no', 'bad', 'dislike'], category: 'People' },
  { emoji: '✊', name: 'raised fist', keywords: ['punch', 'power'], category: 'People' },
  { emoji: '👊', name: 'fist bump', keywords: ['punch', 'bump'], category: 'People' },
  { emoji: '🤛', name: 'left fist', keywords: ['fist bump'], category: 'People' },
  { emoji: '🤜', name: 'right fist', keywords: ['fist bump'], category: 'People' },
  { emoji: '👏', name: 'clapping hands', keywords: ['applause', 'clap', 'bravo'], category: 'People' },
  { emoji: '🙌', name: 'raising hands', keywords: ['hooray', 'celebrate'], category: 'People' },
  { emoji: '🫶', name: 'heart hands', keywords: ['love', 'heart'], category: 'People' },
  { emoji: '👐', name: 'open hands', keywords: ['jazz hands'], category: 'People' },
  { emoji: '🤲', name: 'palms up together', keywords: ['pray', 'please'], category: 'People' },
  { emoji: '🤝', name: 'handshake', keywords: ['agree', 'deal'], category: 'People' },
  { emoji: '🙏', name: 'folded hands', keywords: ['pray', 'please', 'thanks'], category: 'People' },
  { emoji: '✍️', name: 'writing hand', keywords: ['write', 'pen'], category: 'People' },
  { emoji: '💪', name: 'flexed biceps', keywords: ['strong', 'muscle', 'gym'], category: 'People' },
  { emoji: '🦾', name: 'mechanical arm', keywords: ['robot', 'prosthetic'], category: 'People' },
  { emoji: '🧠', name: 'brain', keywords: ['smart', 'think', 'mind'], category: 'People' },
  { emoji: '👀', name: 'eyes', keywords: ['look', 'see', 'watch'], category: 'People' },
  { emoji: '👁️', name: 'eye', keywords: ['look', 'see'], category: 'People' },
  { emoji: '👅', name: 'tongue', keywords: ['lick', 'taste'], category: 'People' },
  { emoji: '👄', name: 'mouth', keywords: ['lips', 'kiss'], category: 'People' },
  { emoji: '🫦', name: 'biting lip', keywords: ['nervous', 'flirt'], category: 'People' },
  { emoji: '👶', name: 'baby', keywords: ['child', 'infant'], category: 'People' },
  { emoji: '🧒', name: 'child', keywords: ['kid', 'young'], category: 'People' },
  { emoji: '👦', name: 'boy', keywords: ['male', 'kid'], category: 'People' },
  { emoji: '👧', name: 'girl', keywords: ['female', 'kid'], category: 'People' },
  { emoji: '🧑', name: 'person', keywords: ['adult'], category: 'People' },
  { emoji: '👨', name: 'man', keywords: ['male', 'adult'], category: 'People' },
  { emoji: '👩', name: 'woman', keywords: ['female', 'adult'], category: 'People' },
  { emoji: '🧑‍💻', name: 'technologist', keywords: ['developer', 'coder', 'programmer'], category: 'People' },
  { emoji: '👨‍💻', name: 'man technologist', keywords: ['developer', 'programmer'], category: 'People' },
  { emoji: '👩‍💻', name: 'woman technologist', keywords: ['developer', 'programmer'], category: 'People' },
  { emoji: '🧑‍🎨', name: 'artist', keywords: ['painter', 'creative'], category: 'People' },
  { emoji: '🧑‍🚀', name: 'astronaut', keywords: ['space', 'rocket'], category: 'People' },
  { emoji: '🧑‍🔬', name: 'scientist', keywords: ['research', 'lab'], category: 'People' },
  { emoji: '🥷', name: 'ninja', keywords: ['stealth', 'hidden'], category: 'People' },
  { emoji: '🧙', name: 'mage', keywords: ['wizard', 'magic'], category: 'People' },
  { emoji: '🧛', name: 'vampire', keywords: ['dracula', 'halloween'], category: 'People' },
  { emoji: '🧟', name: 'zombie', keywords: ['undead', 'halloween'], category: 'People' },
  { emoji: '🏃', name: 'running person', keywords: ['run', 'exercise', 'sprint'], category: 'People' },
  { emoji: '💃', name: 'dancing woman', keywords: ['dance', 'party'], category: 'People' },
  { emoji: '🕺', name: 'dancing man', keywords: ['dance', 'party'], category: 'People' },
  { emoji: '🤷', name: 'shrug', keywords: ['idk', 'whatever', 'dunno'], category: 'People' },
  { emoji: '🤦', name: 'face palm', keywords: ['facepalm', 'smh'], category: 'People' },
  { emoji: '🧘', name: 'person in lotus', keywords: ['yoga', 'meditate'], category: 'People' },

  // Animals
  { emoji: '🐶', name: 'dog face', keywords: ['puppy', 'pet', 'woof'], category: 'Animals' },
  { emoji: '🐱', name: 'cat face', keywords: ['kitten', 'pet', 'meow'], category: 'Animals' },
  { emoji: '🐭', name: 'mouse face', keywords: ['rodent'], category: 'Animals' },
  { emoji: '🐹', name: 'hamster', keywords: ['pet', 'rodent'], category: 'Animals' },
  { emoji: '🐰', name: 'rabbit face', keywords: ['bunny', 'pet'], category: 'Animals' },
  { emoji: '🦊', name: 'fox', keywords: ['clever', 'cunning'], category: 'Animals' },
  { emoji: '🐻', name: 'bear', keywords: ['teddy', 'animal'], category: 'Animals' },
  { emoji: '🐼', name: 'panda', keywords: ['bear', 'cute'], category: 'Animals' },
  { emoji: '🐻‍❄️', name: 'polar bear', keywords: ['arctic', 'cold'], category: 'Animals' },
  { emoji: '🐨', name: 'koala', keywords: ['australia', 'cute'], category: 'Animals' },
  { emoji: '🐯', name: 'tiger face', keywords: ['big cat', 'wild'], category: 'Animals' },
  { emoji: '🦁', name: 'lion', keywords: ['king', 'wild', 'big cat'], category: 'Animals' },
  { emoji: '🐮', name: 'cow face', keywords: ['moo', 'farm'], category: 'Animals' },
  { emoji: '🐷', name: 'pig face', keywords: ['oink', 'farm'], category: 'Animals' },
  { emoji: '🐸', name: 'frog', keywords: ['toad', 'ribbit'], category: 'Animals' },
  { emoji: '🐵', name: 'monkey face', keywords: ['ape', 'primate'], category: 'Animals' },
  { emoji: '🙈', name: 'see no evil monkey', keywords: ['hide', 'shy'], category: 'Animals' },
  { emoji: '🙉', name: 'hear no evil monkey', keywords: ['ignore'], category: 'Animals' },
  { emoji: '🙊', name: 'speak no evil monkey', keywords: ['quiet', 'oops'], category: 'Animals' },
  { emoji: '🐔', name: 'chicken', keywords: ['hen', 'farm', 'poultry'], category: 'Animals' },
  { emoji: '🐧', name: 'penguin', keywords: ['arctic', 'cold', 'linux'], category: 'Animals' },
  { emoji: '🐦', name: 'bird', keywords: ['tweet', 'fly'], category: 'Animals' },
  { emoji: '🦅', name: 'eagle', keywords: ['bird', 'america'], category: 'Animals' },
  { emoji: '🦆', name: 'duck', keywords: ['bird', 'quack'], category: 'Animals' },
  { emoji: '🦉', name: 'owl', keywords: ['wise', 'bird', 'night'], category: 'Animals' },
  { emoji: '🦇', name: 'bat', keywords: ['vampire', 'night'], category: 'Animals' },
  { emoji: '🐺', name: 'wolf', keywords: ['howl', 'wild'], category: 'Animals' },
  { emoji: '🐗', name: 'boar', keywords: ['pig', 'wild'], category: 'Animals' },
  { emoji: '🐴', name: 'horse face', keywords: ['pony', 'neigh'], category: 'Animals' },
  { emoji: '🦄', name: 'unicorn', keywords: ['magic', 'fantasy', 'rainbow'], category: 'Animals' },
  { emoji: '🐝', name: 'honeybee', keywords: ['bee', 'buzz', 'honey'], category: 'Animals' },
  { emoji: '🪱', name: 'worm', keywords: ['bug', 'earth'], category: 'Animals' },
  { emoji: '🐛', name: 'bug', keywords: ['insect', 'caterpillar'], category: 'Animals' },
  { emoji: '🦋', name: 'butterfly', keywords: ['insect', 'pretty'], category: 'Animals' },
  { emoji: '🐌', name: 'snail', keywords: ['slow'], category: 'Animals' },
  { emoji: '🐙', name: 'octopus', keywords: ['tentacles', 'sea'], category: 'Animals' },
  { emoji: '🦑', name: 'squid', keywords: ['tentacles', 'sea'], category: 'Animals' },
  { emoji: '🦀', name: 'crab', keywords: ['sea', 'beach'], category: 'Animals' },
  { emoji: '🐠', name: 'tropical fish', keywords: ['fish', 'sea'], category: 'Animals' },
  { emoji: '🐬', name: 'dolphin', keywords: ['sea', 'smart', 'ocean'], category: 'Animals' },
  { emoji: '🐳', name: 'spouting whale', keywords: ['ocean', 'sea'], category: 'Animals' },
  { emoji: '🦈', name: 'shark', keywords: ['ocean', 'danger', 'jaws'], category: 'Animals' },
  { emoji: '🐊', name: 'crocodile', keywords: ['alligator', 'reptile'], category: 'Animals' },
  { emoji: '🐢', name: 'turtle', keywords: ['slow', 'shell'], category: 'Animals' },
  { emoji: '🦎', name: 'lizard', keywords: ['reptile'], category: 'Animals' },
  { emoji: '🐍', name: 'snake', keywords: ['hiss', 'reptile'], category: 'Animals' },
  { emoji: '🦖', name: 'trex', keywords: ['dinosaur', 'jurassic'], category: 'Animals' },
  { emoji: '🦕', name: 'sauropod', keywords: ['dinosaur', 'brontosaurus'], category: 'Animals' },
  { emoji: '🐉', name: 'dragon', keywords: ['fire', 'fantasy', 'mythical'], category: 'Animals' },
  { emoji: '🌸', name: 'cherry blossom', keywords: ['flower', 'spring', 'pink'], category: 'Animals' },
  { emoji: '🌹', name: 'rose', keywords: ['flower', 'love', 'romance'], category: 'Animals' },
  { emoji: '🌻', name: 'sunflower', keywords: ['flower', 'sun'], category: 'Animals' },
  { emoji: '🌺', name: 'hibiscus', keywords: ['flower', 'tropical'], category: 'Animals' },
  { emoji: '🍀', name: 'four leaf clover', keywords: ['luck', 'irish'], category: 'Animals' },
  { emoji: '🌲', name: 'evergreen tree', keywords: ['tree', 'forest', 'pine'], category: 'Animals' },
  { emoji: '🌴', name: 'palm tree', keywords: ['tropical', 'beach'], category: 'Animals' },
  { emoji: '🌵', name: 'cactus', keywords: ['desert', 'plant'], category: 'Animals' },
  { emoji: '🍄', name: 'mushroom', keywords: ['fungus', 'toadstool'], category: 'Animals' },

  // Food
  { emoji: '🍎', name: 'red apple', keywords: ['fruit', 'healthy'], category: 'Food' },
  { emoji: '🍊', name: 'tangerine', keywords: ['orange', 'fruit'], category: 'Food' },
  { emoji: '🍋', name: 'lemon', keywords: ['citrus', 'sour'], category: 'Food' },
  { emoji: '🍌', name: 'banana', keywords: ['fruit'], category: 'Food' },
  { emoji: '🍉', name: 'watermelon', keywords: ['fruit', 'summer'], category: 'Food' },
  { emoji: '🍇', name: 'grapes', keywords: ['fruit', 'wine'], category: 'Food' },
  { emoji: '🍓', name: 'strawberry', keywords: ['fruit', 'berry'], category: 'Food' },
  { emoji: '🫐', name: 'blueberries', keywords: ['fruit', 'berry'], category: 'Food' },
  { emoji: '🍑', name: 'peach', keywords: ['fruit'], category: 'Food' },
  { emoji: '🥭', name: 'mango', keywords: ['fruit', 'tropical'], category: 'Food' },
  { emoji: '🍍', name: 'pineapple', keywords: ['fruit', 'tropical'], category: 'Food' },
  { emoji: '🥝', name: 'kiwi fruit', keywords: ['fruit'], category: 'Food' },
  { emoji: '🍅', name: 'tomato', keywords: ['vegetable', 'fruit'], category: 'Food' },
  { emoji: '🥑', name: 'avocado', keywords: ['fruit', 'guacamole'], category: 'Food' },
  { emoji: '🥦', name: 'broccoli', keywords: ['vegetable', 'healthy'], category: 'Food' },
  { emoji: '🥬', name: 'leafy green', keywords: ['vegetable', 'salad'], category: 'Food' },
  { emoji: '🌽', name: 'corn', keywords: ['vegetable', 'maize'], category: 'Food' },
  { emoji: '🌶️', name: 'hot pepper', keywords: ['spicy', 'chili'], category: 'Food' },
  { emoji: '🥕', name: 'carrot', keywords: ['vegetable', 'orange'], category: 'Food' },
  { emoji: '🧄', name: 'garlic', keywords: ['cooking', 'vampire'], category: 'Food' },
  { emoji: '🧅', name: 'onion', keywords: ['cooking', 'cry'], category: 'Food' },
  { emoji: '🥔', name: 'potato', keywords: ['vegetable', 'fry'], category: 'Food' },
  { emoji: '🍞', name: 'bread', keywords: ['toast', 'carbs'], category: 'Food' },
  { emoji: '🥐', name: 'croissant', keywords: ['bread', 'french', 'pastry'], category: 'Food' },
  { emoji: '🥖', name: 'baguette', keywords: ['bread', 'french'], category: 'Food' },
  { emoji: '🧀', name: 'cheese', keywords: ['dairy'], category: 'Food' },
  { emoji: '🥚', name: 'egg', keywords: ['breakfast'], category: 'Food' },
  { emoji: '🍳', name: 'cooking', keywords: ['egg', 'frying pan', 'breakfast'], category: 'Food' },
  { emoji: '🥓', name: 'bacon', keywords: ['meat', 'breakfast', 'pork'], category: 'Food' },
  { emoji: '🥩', name: 'steak', keywords: ['meat', 'beef'], category: 'Food' },
  { emoji: '🍗', name: 'poultry leg', keywords: ['chicken', 'meat'], category: 'Food' },
  { emoji: '🍔', name: 'hamburger', keywords: ['burger', 'fast food'], category: 'Food' },
  { emoji: '🍟', name: 'french fries', keywords: ['fries', 'fast food'], category: 'Food' },
  { emoji: '🍕', name: 'pizza', keywords: ['food', 'italian'], category: 'Food' },
  { emoji: '🌭', name: 'hot dog', keywords: ['sausage', 'fast food'], category: 'Food' },
  { emoji: '🥪', name: 'sandwich', keywords: ['lunch', 'bread'], category: 'Food' },
  { emoji: '🌮', name: 'taco', keywords: ['mexican', 'food'], category: 'Food' },
  { emoji: '🌯', name: 'burrito', keywords: ['mexican', 'wrap'], category: 'Food' },
  { emoji: '🥗', name: 'green salad', keywords: ['healthy', 'vegetable'], category: 'Food' },
  { emoji: '🍜', name: 'steaming bowl', keywords: ['noodles', 'ramen', 'soup'], category: 'Food' },
  { emoji: '🍝', name: 'spaghetti', keywords: ['pasta', 'italian'], category: 'Food' },
  { emoji: '🍣', name: 'sushi', keywords: ['japanese', 'fish'], category: 'Food' },
  { emoji: '🍱', name: 'bento box', keywords: ['japanese', 'lunch'], category: 'Food' },
  { emoji: '🥟', name: 'dumpling', keywords: ['asian', 'food'], category: 'Food' },
  { emoji: '🍦', name: 'soft ice cream', keywords: ['dessert', 'sweet'], category: 'Food' },
  { emoji: '🍧', name: 'shaved ice', keywords: ['dessert', 'sweet'], category: 'Food' },
  { emoji: '🍰', name: 'shortcake', keywords: ['cake', 'dessert', 'birthday'], category: 'Food' },
  { emoji: '🎂', name: 'birthday cake', keywords: ['cake', 'birthday', 'party'], category: 'Food' },
  { emoji: '🧁', name: 'cupcake', keywords: ['dessert', 'sweet'], category: 'Food' },
  { emoji: '🍫', name: 'chocolate bar', keywords: ['candy', 'sweet'], category: 'Food' },
  { emoji: '🍬', name: 'candy', keywords: ['sweet'], category: 'Food' },
  { emoji: '🍭', name: 'lollipop', keywords: ['candy', 'sweet'], category: 'Food' },
  { emoji: '🍩', name: 'doughnut', keywords: ['donut', 'dessert'], category: 'Food' },
  { emoji: '🍪', name: 'cookie', keywords: ['biscuit', 'sweet'], category: 'Food' },
  { emoji: '☕', name: 'hot beverage', keywords: ['coffee', 'tea'], category: 'Food' },
  { emoji: '🍵', name: 'teacup', keywords: ['tea', 'drink'], category: 'Food' },
  { emoji: '🧃', name: 'beverage box', keywords: ['juice', 'drink'], category: 'Food' },
  { emoji: '🥤', name: 'cup with straw', keywords: ['soda', 'drink'], category: 'Food' },
  { emoji: '🧋', name: 'bubble tea', keywords: ['boba', 'drink'], category: 'Food' },
  { emoji: '🍺', name: 'beer mug', keywords: ['drink', 'alcohol'], category: 'Food' },
  { emoji: '🍻', name: 'clinking beer mugs', keywords: ['cheers', 'drink'], category: 'Food' },
  { emoji: '🥂', name: 'clinking glasses', keywords: ['cheers', 'celebrate', 'champagne'], category: 'Food' },
  { emoji: '🍷', name: 'wine glass', keywords: ['drink', 'alcohol'], category: 'Food' },
  { emoji: '🍸', name: 'cocktail glass', keywords: ['drink', 'martini'], category: 'Food' },

  // Activities
  { emoji: '⚽', name: 'soccer ball', keywords: ['football', 'sport'], category: 'Activities' },
  { emoji: '🏀', name: 'basketball', keywords: ['sport', 'hoop'], category: 'Activities' },
  { emoji: '🏈', name: 'american football', keywords: ['sport', 'nfl'], category: 'Activities' },
  { emoji: '⚾', name: 'baseball', keywords: ['sport'], category: 'Activities' },
  { emoji: '🥎', name: 'softball', keywords: ['sport'], category: 'Activities' },
  { emoji: '🎾', name: 'tennis', keywords: ['sport', 'racket'], category: 'Activities' },
  { emoji: '🏐', name: 'volleyball', keywords: ['sport'], category: 'Activities' },
  { emoji: '🏉', name: 'rugby football', keywords: ['sport'], category: 'Activities' },
  { emoji: '🥏', name: 'flying disc', keywords: ['frisbee', 'sport'], category: 'Activities' },
  { emoji: '🎱', name: 'pool 8 ball', keywords: ['billiards', 'game'], category: 'Activities' },
  { emoji: '🏓', name: 'ping pong', keywords: ['table tennis', 'sport'], category: 'Activities' },
  { emoji: '🏸', name: 'badminton', keywords: ['sport', 'racket'], category: 'Activities' },
  { emoji: '🏒', name: 'ice hockey', keywords: ['sport', 'hockey'], category: 'Activities' },
  { emoji: '⛳', name: 'flag in hole', keywords: ['golf', 'sport'], category: 'Activities' },
  { emoji: '🏹', name: 'bow and arrow', keywords: ['archery', 'sport'], category: 'Activities' },
  { emoji: '🎣', name: 'fishing pole', keywords: ['fish', 'sport'], category: 'Activities' },
  { emoji: '🥊', name: 'boxing glove', keywords: ['boxing', 'fight', 'sport'], category: 'Activities' },
  { emoji: '🥋', name: 'martial arts uniform', keywords: ['karate', 'judo'], category: 'Activities' },
  { emoji: '🎿', name: 'skis', keywords: ['skiing', 'winter', 'sport'], category: 'Activities' },
  { emoji: '⛷️', name: 'skier', keywords: ['skiing', 'winter'], category: 'Activities' },
  { emoji: '🏂', name: 'snowboarder', keywords: ['snowboard', 'winter'], category: 'Activities' },
  { emoji: '🏋️', name: 'weight lifter', keywords: ['gym', 'exercise', 'workout'], category: 'Activities' },
  { emoji: '🚴', name: 'bicyclist', keywords: ['bike', 'cycling', 'exercise'], category: 'Activities' },
  { emoji: '🧗', name: 'person climbing', keywords: ['climb', 'rock'], category: 'Activities' },
  { emoji: '🏄', name: 'surfer', keywords: ['surf', 'wave', 'beach'], category: 'Activities' },
  { emoji: '🏊', name: 'swimmer', keywords: ['swim', 'pool', 'water'], category: 'Activities' },
  { emoji: '🎮', name: 'video game', keywords: ['gaming', 'controller', 'play'], category: 'Activities' },
  { emoji: '🕹️', name: 'joystick', keywords: ['gaming', 'arcade', 'retro'], category: 'Activities' },
  { emoji: '🎲', name: 'game die', keywords: ['dice', 'roll', 'random'], category: 'Activities' },
  { emoji: '🧩', name: 'puzzle piece', keywords: ['jigsaw', 'game'], category: 'Activities' },
  { emoji: '♟️', name: 'chess pawn', keywords: ['chess', 'game', 'strategy'], category: 'Activities' },
  { emoji: '🎯', name: 'direct hit', keywords: ['target', 'bullseye', 'dart'], category: 'Activities' },
  { emoji: '🎳', name: 'bowling', keywords: ['sport', 'game'], category: 'Activities' },
  { emoji: '🎪', name: 'circus tent', keywords: ['circus', 'show'], category: 'Activities' },
  { emoji: '🎭', name: 'performing arts', keywords: ['theater', 'drama', 'masks'], category: 'Activities' },
  { emoji: '🎨', name: 'artist palette', keywords: ['art', 'paint', 'creative'], category: 'Activities' },
  { emoji: '🎬', name: 'clapper board', keywords: ['movie', 'film', 'cinema'], category: 'Activities' },
  { emoji: '🎤', name: 'microphone', keywords: ['sing', 'karaoke', 'music'], category: 'Activities' },
  { emoji: '🎧', name: 'headphone', keywords: ['music', 'listen', 'audio'], category: 'Activities' },
  { emoji: '🎼', name: 'musical score', keywords: ['music', 'notes'], category: 'Activities' },
  { emoji: '🎹', name: 'musical keyboard', keywords: ['piano', 'music'], category: 'Activities' },
  { emoji: '🎸', name: 'guitar', keywords: ['music', 'rock'], category: 'Activities' },
  { emoji: '🎺', name: 'trumpet', keywords: ['music', 'jazz'], category: 'Activities' },
  { emoji: '🥁', name: 'drum', keywords: ['music', 'beat'], category: 'Activities' },
  { emoji: '🎵', name: 'musical note', keywords: ['music', 'song'], category: 'Activities' },
  { emoji: '🎶', name: 'musical notes', keywords: ['music', 'melody'], category: 'Activities' },
  { emoji: '🏆', name: 'trophy', keywords: ['win', 'award', 'champion'], category: 'Activities' },
  { emoji: '🥇', name: 'gold medal', keywords: ['first', 'winner'], category: 'Activities' },
  { emoji: '🥈', name: 'silver medal', keywords: ['second', 'runner up'], category: 'Activities' },
  { emoji: '🥉', name: 'bronze medal', keywords: ['third'], category: 'Activities' },
  { emoji: '🎖️', name: 'military medal', keywords: ['honor', 'award'], category: 'Activities' },
  { emoji: '🎗️', name: 'reminder ribbon', keywords: ['awareness'], category: 'Activities' },
  { emoji: '🎟️', name: 'admission tickets', keywords: ['ticket', 'event'], category: 'Activities' },
  { emoji: '🎉', name: 'party popper', keywords: ['celebrate', 'party', 'tada'], category: 'Activities' },
  { emoji: '🎊', name: 'confetti ball', keywords: ['celebrate', 'party'], category: 'Activities' },
  { emoji: '🎈', name: 'balloon', keywords: ['party', 'birthday'], category: 'Activities' },
  { emoji: '🎁', name: 'wrapped gift', keywords: ['present', 'birthday'], category: 'Activities' },
  { emoji: '🎄', name: 'christmas tree', keywords: ['holiday', 'xmas'], category: 'Activities' },
  { emoji: '🎃', name: 'jack-o-lantern', keywords: ['halloween', 'pumpkin'], category: 'Activities' },
  { emoji: '🎆', name: 'fireworks', keywords: ['celebrate', 'new year'], category: 'Activities' },
  { emoji: '✨', name: 'sparkles', keywords: ['shine', 'glitter', 'magic'], category: 'Activities' },
  { emoji: '🎀', name: 'ribbon', keywords: ['bow', 'gift'], category: 'Activities' },

  // Travel
  { emoji: '🚗', name: 'automobile', keywords: ['car', 'drive', 'vehicle'], category: 'Travel' },
  { emoji: '🚕', name: 'taxi', keywords: ['cab', 'car'], category: 'Travel' },
  { emoji: '🚌', name: 'bus', keywords: ['transit', 'vehicle'], category: 'Travel' },
  { emoji: '🚎', name: 'trolleybus', keywords: ['bus', 'transit'], category: 'Travel' },
  { emoji: '🏎️', name: 'racing car', keywords: ['fast', 'f1'], category: 'Travel' },
  { emoji: '🚓', name: 'police car', keywords: ['cop', 'law'], category: 'Travel' },
  { emoji: '🚑', name: 'ambulance', keywords: ['hospital', 'emergency'], category: 'Travel' },
  { emoji: '🚒', name: 'fire engine', keywords: ['fire', 'emergency'], category: 'Travel' },
  { emoji: '🚐', name: 'minibus', keywords: ['van', 'vehicle'], category: 'Travel' },
  { emoji: '🛻', name: 'pickup truck', keywords: ['truck', 'vehicle'], category: 'Travel' },
  { emoji: '🚲', name: 'bicycle', keywords: ['bike', 'cycling'], category: 'Travel' },
  { emoji: '🛵', name: 'motor scooter', keywords: ['vespa', 'scooter'], category: 'Travel' },
  { emoji: '🏍️', name: 'motorcycle', keywords: ['bike', 'motorbike'], category: 'Travel' },
  { emoji: '✈️', name: 'airplane', keywords: ['fly', 'travel', 'plane'], category: 'Travel' },
  { emoji: '🚀', name: 'rocket', keywords: ['space', 'launch', 'fast'], category: 'Travel' },
  { emoji: '🛸', name: 'flying saucer', keywords: ['ufo', 'alien'], category: 'Travel' },
  { emoji: '🚁', name: 'helicopter', keywords: ['fly', 'chopper'], category: 'Travel' },
  { emoji: '🛶', name: 'canoe', keywords: ['boat', 'kayak'], category: 'Travel' },
  { emoji: '⛵', name: 'sailboat', keywords: ['boat', 'sail'], category: 'Travel' },
  { emoji: '🚢', name: 'ship', keywords: ['boat', 'cruise'], category: 'Travel' },
  { emoji: '🚂', name: 'locomotive', keywords: ['train', 'steam'], category: 'Travel' },
  { emoji: '🚆', name: 'train', keywords: ['transit', 'rail'], category: 'Travel' },
  { emoji: '🏠', name: 'house', keywords: ['home', 'building'], category: 'Travel' },
  { emoji: '🏡', name: 'house with garden', keywords: ['home', 'garden'], category: 'Travel' },
  { emoji: '🏢', name: 'office building', keywords: ['work', 'business'], category: 'Travel' },
  { emoji: '🏥', name: 'hospital', keywords: ['health', 'medical'], category: 'Travel' },
  { emoji: '🏫', name: 'school', keywords: ['education', 'learn'], category: 'Travel' },
  { emoji: '🏰', name: 'castle', keywords: ['medieval', 'royalty'], category: 'Travel' },
  { emoji: '🗼', name: 'tokyo tower', keywords: ['japan', 'landmark'], category: 'Travel' },
  { emoji: '🗽', name: 'statue of liberty', keywords: ['nyc', 'america'], category: 'Travel' },
  { emoji: '⛩️', name: 'shinto shrine', keywords: ['japan', 'temple'], category: 'Travel' },
  { emoji: '🌍', name: 'earth africa', keywords: ['world', 'globe', 'planet'], category: 'Travel' },
  { emoji: '🌎', name: 'earth americas', keywords: ['world', 'globe', 'planet'], category: 'Travel' },
  { emoji: '🌏', name: 'earth asia', keywords: ['world', 'globe', 'planet'], category: 'Travel' },
  { emoji: '🌙', name: 'crescent moon', keywords: ['moon', 'night'], category: 'Travel' },
  { emoji: '🌝', name: 'full moon face', keywords: ['moon', 'night'], category: 'Travel' },
  { emoji: '⭐', name: 'star', keywords: ['night', 'sky', 'shine'], category: 'Travel' },
  { emoji: '🌟', name: 'glowing star', keywords: ['shine', 'sparkle'], category: 'Travel' },
  { emoji: '☀️', name: 'sun', keywords: ['sunny', 'weather', 'hot'], category: 'Travel' },
  { emoji: '🌤️', name: 'sun behind small cloud', keywords: ['weather', 'partly cloudy'], category: 'Travel' },
  { emoji: '⛅', name: 'sun behind cloud', keywords: ['weather', 'cloudy'], category: 'Travel' },
  { emoji: '🌧️', name: 'cloud with rain', keywords: ['weather', 'rainy'], category: 'Travel' },
  { emoji: '⛈️', name: 'cloud with lightning and rain', keywords: ['storm', 'weather'], category: 'Travel' },
  { emoji: '🌩️', name: 'cloud with lightning', keywords: ['storm', 'thunder'], category: 'Travel' },
  { emoji: '❄️', name: 'snowflake', keywords: ['cold', 'winter', 'snow'], category: 'Travel' },
  { emoji: '🌈', name: 'rainbow', keywords: ['colorful', 'pride'], category: 'Travel' },
  { emoji: '🔥', name: 'fire', keywords: ['hot', 'flame', 'lit'], category: 'Travel' },
  { emoji: '💧', name: 'droplet', keywords: ['water', 'rain'], category: 'Travel' },
  { emoji: '🌊', name: 'water wave', keywords: ['ocean', 'sea', 'surf'], category: 'Travel' },
  { emoji: '⛰️', name: 'mountain', keywords: ['nature', 'hike'], category: 'Travel' },
  { emoji: '🏔️', name: 'snow capped mountain', keywords: ['nature', 'cold'], category: 'Travel' },
  { emoji: '🏖️', name: 'beach', keywords: ['sand', 'vacation', 'summer'], category: 'Travel' },
  { emoji: '🏕️', name: 'camping', keywords: ['tent', 'outdoors', 'nature'], category: 'Travel' },

  // Objects
  { emoji: '⌚', name: 'watch', keywords: ['time', 'clock'], category: 'Objects' },
  { emoji: '📱', name: 'mobile phone', keywords: ['cell', 'iphone', 'smartphone'], category: 'Objects' },
  { emoji: '💻', name: 'laptop', keywords: ['computer', 'pc', 'mac'], category: 'Objects' },
  { emoji: '⌨️', name: 'keyboard', keywords: ['type', 'computer'], category: 'Objects' },
  { emoji: '🖥️', name: 'desktop computer', keywords: ['monitor', 'pc'], category: 'Objects' },
  { emoji: '🖨️', name: 'printer', keywords: ['print', 'office'], category: 'Objects' },
  { emoji: '🖱️', name: 'computer mouse', keywords: ['click'], category: 'Objects' },
  { emoji: '💾', name: 'floppy disk', keywords: ['save', 'retro'], category: 'Objects' },
  { emoji: '💿', name: 'optical disk', keywords: ['cd', 'dvd'], category: 'Objects' },
  { emoji: '📀', name: 'dvd', keywords: ['disk', 'movie'], category: 'Objects' },
  { emoji: '📷', name: 'camera', keywords: ['photo', 'picture'], category: 'Objects' },
  { emoji: '🎥', name: 'movie camera', keywords: ['film', 'video'], category: 'Objects' },
  { emoji: '📺', name: 'television', keywords: ['tv', 'watch'], category: 'Objects' },
  { emoji: '📻', name: 'radio', keywords: ['music', 'listen'], category: 'Objects' },
  { emoji: '🔋', name: 'battery', keywords: ['power', 'energy'], category: 'Objects' },
  { emoji: '🔌', name: 'electric plug', keywords: ['power', 'charge'], category: 'Objects' },
  { emoji: '💡', name: 'light bulb', keywords: ['idea', 'bright'], category: 'Objects' },
  { emoji: '🔦', name: 'flashlight', keywords: ['light', 'torch'], category: 'Objects' },
  { emoji: '🕯️', name: 'candle', keywords: ['light', 'flame'], category: 'Objects' },
  { emoji: '📖', name: 'open book', keywords: ['read', 'literature'], category: 'Objects' },
  { emoji: '📚', name: 'books', keywords: ['read', 'library', 'study'], category: 'Objects' },
  { emoji: '📝', name: 'memo', keywords: ['write', 'note', 'pencil'], category: 'Objects' },
  { emoji: '📎', name: 'paperclip', keywords: ['attach', 'office'], category: 'Objects' },
  { emoji: '📏', name: 'straight ruler', keywords: ['measure', 'math'], category: 'Objects' },
  { emoji: '📐', name: 'triangular ruler', keywords: ['measure', 'math'], category: 'Objects' },
  { emoji: '✂️', name: 'scissors', keywords: ['cut'], category: 'Objects' },
  { emoji: '🔑', name: 'key', keywords: ['lock', 'password', 'security'], category: 'Objects' },
  { emoji: '🗝️', name: 'old key', keywords: ['lock', 'vintage'], category: 'Objects' },
  { emoji: '🔒', name: 'locked', keywords: ['security', 'lock', 'private'], category: 'Objects' },
  { emoji: '🔓', name: 'unlocked', keywords: ['security', 'open'], category: 'Objects' },
  { emoji: '🔐', name: 'locked with key', keywords: ['security', 'encrypted'], category: 'Objects' },
  { emoji: '🔔', name: 'bell', keywords: ['notification', 'alert'], category: 'Objects' },
  { emoji: '🔕', name: 'bell with slash', keywords: ['mute', 'silent'], category: 'Objects' },
  { emoji: '🔗', name: 'link', keywords: ['chain', 'url'], category: 'Objects' },
  { emoji: '⚙️', name: 'gear', keywords: ['settings', 'config'], category: 'Objects' },
  { emoji: '🧰', name: 'toolbox', keywords: ['tools', 'fix'], category: 'Objects' },
  { emoji: '🔧', name: 'wrench', keywords: ['tool', 'fix'], category: 'Objects' },
  { emoji: '🔨', name: 'hammer', keywords: ['tool', 'build'], category: 'Objects' },
  { emoji: '⚒️', name: 'hammer and pick', keywords: ['tool', 'build'], category: 'Objects' },
  { emoji: '🛡️', name: 'shield', keywords: ['protect', 'security'], category: 'Objects' },
  { emoji: '🧲', name: 'magnet', keywords: ['attract'], category: 'Objects' },
  { emoji: '🧪', name: 'test tube', keywords: ['science', 'experiment'], category: 'Objects' },
  { emoji: '🧬', name: 'dna', keywords: ['science', 'genetics'], category: 'Objects' },
  { emoji: '🔬', name: 'microscope', keywords: ['science', 'research'], category: 'Objects' },
  { emoji: '🔭', name: 'telescope', keywords: ['space', 'astronomy'], category: 'Objects' },
  { emoji: '📡', name: 'satellite antenna', keywords: ['signal', 'broadcast'], category: 'Objects' },
  { emoji: '💉', name: 'syringe', keywords: ['medical', 'vaccine'], category: 'Objects' },
  { emoji: '💊', name: 'pill', keywords: ['medicine', 'drug'], category: 'Objects' },
  { emoji: '🩹', name: 'adhesive bandage', keywords: ['band-aid', 'heal'], category: 'Objects' },
  { emoji: '🏷️', name: 'label', keywords: ['tag', 'price'], category: 'Objects' },
  { emoji: '💰', name: 'money bag', keywords: ['rich', 'wealth', 'cash'], category: 'Objects' },
  { emoji: '💳', name: 'credit card', keywords: ['payment', 'buy'], category: 'Objects' },
  { emoji: '💎', name: 'gem stone', keywords: ['diamond', 'jewel', 'precious'], category: 'Objects' },
  { emoji: '🎙️', name: 'studio microphone', keywords: ['podcast', 'record'], category: 'Objects' },
  { emoji: '📦', name: 'package', keywords: ['box', 'shipping', 'delivery'], category: 'Objects' },
  { emoji: '📬', name: 'mailbox with mail', keywords: ['email', 'letter'], category: 'Objects' },
  { emoji: '📧', name: 'e-mail', keywords: ['email', 'message'], category: 'Objects' },
  { emoji: '🗑️', name: 'wastebasket', keywords: ['trash', 'delete', 'bin'], category: 'Objects' },

  // Symbols
  { emoji: '❤️', name: 'red heart', keywords: ['love'], category: 'Symbols' },
  { emoji: '🧡', name: 'orange heart', keywords: ['love'], category: 'Symbols' },
  { emoji: '💛', name: 'yellow heart', keywords: ['love'], category: 'Symbols' },
  { emoji: '💚', name: 'green heart', keywords: ['love'], category: 'Symbols' },
  { emoji: '💙', name: 'blue heart', keywords: ['love'], category: 'Symbols' },
  { emoji: '💜', name: 'purple heart', keywords: ['love'], category: 'Symbols' },
  { emoji: '🖤', name: 'black heart', keywords: ['love', 'dark'], category: 'Symbols' },
  { emoji: '🤍', name: 'white heart', keywords: ['love', 'pure'], category: 'Symbols' },
  { emoji: '🤎', name: 'brown heart', keywords: ['love'], category: 'Symbols' },
  { emoji: '💔', name: 'broken heart', keywords: ['sad', 'heartbreak'], category: 'Symbols' },
  { emoji: '❣️', name: 'heart exclamation', keywords: ['love'], category: 'Symbols' },
  { emoji: '💕', name: 'two hearts', keywords: ['love', 'couple'], category: 'Symbols' },
  { emoji: '💞', name: 'revolving hearts', keywords: ['love'], category: 'Symbols' },
  { emoji: '💓', name: 'beating heart', keywords: ['love', 'pulse'], category: 'Symbols' },
  { emoji: '💗', name: 'growing heart', keywords: ['love'], category: 'Symbols' },
  { emoji: '💖', name: 'sparkling heart', keywords: ['love', 'shine'], category: 'Symbols' },
  { emoji: '💘', name: 'heart with arrow', keywords: ['love', 'cupid'], category: 'Symbols' },
  { emoji: '💝', name: 'heart with ribbon', keywords: ['love', 'valentine'], category: 'Symbols' },
  { emoji: '💟', name: 'heart decoration', keywords: ['love'], category: 'Symbols' },
  { emoji: '☮️', name: 'peace symbol', keywords: ['peace', 'hippie'], category: 'Symbols' },
  { emoji: '✝️', name: 'latin cross', keywords: ['christian', 'religion'], category: 'Symbols' },
  { emoji: '☪️', name: 'star and crescent', keywords: ['islam', 'religion'], category: 'Symbols' },
  { emoji: '☯️', name: 'yin yang', keywords: ['balance', 'tao'], category: 'Symbols' },
  { emoji: '✡️', name: 'star of david', keywords: ['jewish', 'religion'], category: 'Symbols' },
  { emoji: '♻️', name: 'recycling symbol', keywords: ['recycle', 'green', 'environment'], category: 'Symbols' },
  { emoji: '⚠️', name: 'warning', keywords: ['alert', 'caution', 'danger'], category: 'Symbols' },
  { emoji: '🚫', name: 'prohibited', keywords: ['no', 'forbidden', 'ban'], category: 'Symbols' },
  { emoji: '❌', name: 'cross mark', keywords: ['no', 'wrong', 'delete'], category: 'Symbols' },
  { emoji: '⭕', name: 'hollow red circle', keywords: ['circle', 'ring'], category: 'Symbols' },
  { emoji: '💢', name: 'anger symbol', keywords: ['angry', 'mad'], category: 'Symbols' },
  { emoji: '♨️', name: 'hot springs', keywords: ['steam', 'spa'], category: 'Symbols' },
  { emoji: '🚷', name: 'no pedestrians', keywords: ['no walking'], category: 'Symbols' },
  { emoji: '📵', name: 'no mobile phones', keywords: ['no phone'], category: 'Symbols' },
  { emoji: '🔞', name: 'no one under eighteen', keywords: ['18+', 'adult'], category: 'Symbols' },
  { emoji: '✅', name: 'check mark', keywords: ['yes', 'done', 'complete'], category: 'Symbols' },
  { emoji: '☑️', name: 'check box', keywords: ['yes', 'done'], category: 'Symbols' },
  { emoji: '✔️', name: 'check mark', keywords: ['yes', 'correct'], category: 'Symbols' },
  { emoji: '❓', name: 'question mark', keywords: ['what', 'confused'], category: 'Symbols' },
  { emoji: '❗', name: 'exclamation mark', keywords: ['important', 'bang'], category: 'Symbols' },
  { emoji: '‼️', name: 'double exclamation', keywords: ['important', 'urgent'], category: 'Symbols' },
  { emoji: '⁉️', name: 'exclamation question', keywords: ['interrobang', 'surprise'], category: 'Symbols' },
  { emoji: '💯', name: 'hundred points', keywords: ['100', 'perfect', 'score'], category: 'Symbols' },
  { emoji: '🔱', name: 'trident emblem', keywords: ['poseidon', 'weapon'], category: 'Symbols' },
  { emoji: '⚜️', name: 'fleur-de-lis', keywords: ['french', 'lily'], category: 'Symbols' },
  { emoji: '🔰', name: 'Japanese symbol for beginner', keywords: ['beginner', 'new'], category: 'Symbols' },
  { emoji: '♾️', name: 'infinity', keywords: ['forever', 'loop', 'unlimited'], category: 'Symbols' },
  { emoji: '💤', name: 'zzz', keywords: ['sleep', 'tired', 'snore'], category: 'Symbols' },
  { emoji: '💬', name: 'speech balloon', keywords: ['chat', 'message', 'talk'], category: 'Symbols' },
  { emoji: '💭', name: 'thought balloon', keywords: ['think', 'bubble'], category: 'Symbols' },
  { emoji: '🗯️', name: 'right anger bubble', keywords: ['angry', 'speech'], category: 'Symbols' },
  { emoji: '🔴', name: 'red circle', keywords: ['circle', 'dot'], category: 'Symbols' },
  { emoji: '🟠', name: 'orange circle', keywords: ['circle', 'dot'], category: 'Symbols' },
  { emoji: '🟡', name: 'yellow circle', keywords: ['circle', 'dot'], category: 'Symbols' },
  { emoji: '🟢', name: 'green circle', keywords: ['circle', 'dot', 'online'], category: 'Symbols' },
  { emoji: '🔵', name: 'blue circle', keywords: ['circle', 'dot'], category: 'Symbols' },
  { emoji: '🟣', name: 'purple circle', keywords: ['circle', 'dot'], category: 'Symbols' },
  { emoji: '⚫', name: 'black circle', keywords: ['circle', 'dot'], category: 'Symbols' },
  { emoji: '⚪', name: 'white circle', keywords: ['circle', 'dot'], category: 'Symbols' },
  { emoji: '🟥', name: 'red square', keywords: ['square'], category: 'Symbols' },
  { emoji: '🟧', name: 'orange square', keywords: ['square'], category: 'Symbols' },
  { emoji: '🟨', name: 'yellow square', keywords: ['square'], category: 'Symbols' },
  { emoji: '🟩', name: 'green square', keywords: ['square'], category: 'Symbols' },
  { emoji: '🟦', name: 'blue square', keywords: ['square'], category: 'Symbols' },
  { emoji: '🟪', name: 'purple square', keywords: ['square'], category: 'Symbols' },
  { emoji: '⬛', name: 'black large square', keywords: ['square'], category: 'Symbols' },
  { emoji: '⬜', name: 'white large square', keywords: ['square'], category: 'Symbols' },
  { emoji: '◾', name: 'black medium small square', keywords: ['square'], category: 'Symbols' },
  { emoji: '◽', name: 'white medium small square', keywords: ['square'], category: 'Symbols' },
  { emoji: '▪️', name: 'black small square', keywords: ['square'], category: 'Symbols' },
  { emoji: '▫️', name: 'white small square', keywords: ['square'], category: 'Symbols' },
  { emoji: '🔶', name: 'large orange diamond', keywords: ['diamond', 'shape'], category: 'Symbols' },
  { emoji: '🔷', name: 'large blue diamond', keywords: ['diamond', 'shape'], category: 'Symbols' },
  { emoji: '🔸', name: 'small orange diamond', keywords: ['diamond', 'shape'], category: 'Symbols' },
  { emoji: '🔹', name: 'small blue diamond', keywords: ['diamond', 'shape'], category: 'Symbols' },
  { emoji: '🔺', name: 'red triangle up', keywords: ['triangle'], category: 'Symbols' },
  { emoji: '🔻', name: 'red triangle down', keywords: ['triangle'], category: 'Symbols' },
  { emoji: '🏁', name: 'chequered flag', keywords: ['race', 'finish'], category: 'Symbols' },
  { emoji: '🚩', name: 'triangular flag', keywords: ['flag', 'red flag'], category: 'Symbols' },
  { emoji: '🏳️', name: 'white flag', keywords: ['surrender'], category: 'Symbols' },
  { emoji: '🏴', name: 'black flag', keywords: ['flag'], category: 'Symbols' },
  { emoji: '🏳️‍🌈', name: 'rainbow flag', keywords: ['pride', 'lgbtq'], category: 'Symbols' },
]

/** Category icons for tab display */
export const CATEGORY_ICONS = {
  'Smileys': '😀',
  'People': '👋',
  'Animals': '🐶',
  'Food': '🍕',
  'Activities': '⚽',
  'Travel': '🚀',
  'Objects': '💡',
  'Symbols': '❤️',
}
